TOP_DIR := $(PWD)
STAGING_DIR ?= $(PWD)/.staging_dir
STAGING_INCLUDE := $(STAGING_DIR)/include
STAGING_LIB := $(STAGING_DIR)/lib

CCFLAGS := -I$(STAGING_INCLUDE)

CCFLAGS += -ggdb -O0

CFLAGS := $(CCFLAGS) -std=c99
CXXFLAGS := $(CCFLAGS) -std=c++11
LDFLAGS := -L$(STAGING_LIB)
INSTALL_DIR := $(STAGING_DIR)
DESTDIR := $(STAGING_DIR)
prefix :=

TOOLCHAIN_PREFIX :=
AR := $(TOOLCHAIN_PREFIX)ar
AS := $(TOOLCHAIN_PREFIX)as
CXX := $(TOOLCHAIN_PREFIX)g++
CC := $(TOOLCHAIN_PREFIX)gcc
NM := $(TOOLCHAIN_PREFIX)nm

export    STAGING_DIR STAGING_INCLUDE STAGING_LIB INSTALL_DIR DESTDIR prefix
export    AR AS CC NM OBJCOPY OBJDUMP CXX
export    CFLAGS CXXFLAGS LDFLAGS
