PROJECT := example/network/uart/uart_tool
EXE_NAME := uart_tool

CPP_SRC_FILES := uart_tool.cpp

CXXFLAGS := -DLOG_MODULE_ID='"$(EXE_NAME)"' $(CXXFLAGS)
LDFLAGS += \
	-ltbox_network \
	-ltbox_event \
	-ltbox_base \

include ${TOP_DIR}/tools/exe_common.mk
