LIB_NAME = log
LIB_VERSION_X = 0
LIB_VERSION_Y = 0
LIB_VERSION_Z = 1

HEAD_FILES = \
	logger.h

SRC_FILES = \
	logger.cpp

CCXXFLAGS += $(CXXFLAGS)

TEST_SRC_FILES = \
	logger_test.cpp

TEST_LDFLAGS := $(LDFLAGS)

ENABLE_SHARED_LIB = no

include ../tools/lib_common.mk
