name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          sudo apt update
          sudo apt install build-essential
          sudo apt install libgtest-dev libgmock-dev libmosquitto-dev
      - uses: actions/checkout@v2
      - name: build
        run: make 3rd-party modules RELEASE=1 STAGING_DIR=$HOME/.tbox
